### ISSUE TITLE
Nezobrazují se soustředění a chybová hláška je superpodrobná

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/dokuwiki-plugin-fksdbexport#1]
Je potřeba zkontrolovat, kde ještě se zobrazují superposrobné logy a co ještě nefunguje.

http://fykos.cz/akce/soustredeni

**Comment by cevro** [comment]
potreba do msg pridať parameter posledný parameter s úrovňou práv na zobrazenie danej hlášky. 

```
msg($message,$lvl=0,$line='',$file='',$allow=MSG_PUBLIC)   X-Ref
Display a message to the user

param: string $message
param: int    $lvl   -1 = error, 0 = info, 1 = success, 2 = notify
param: string $line  line number
param: string $file  file number
param: int    $allow who's allowed to see the message, see MSG_* constants
```

see: http://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/msg.html
