### ISSUE TITLE
JS template nevytváří obsah bez povoleného Java Scriptu (zejména pro vyhledávače)

### ISSUE THREAD

**Issue by Werkov** [fykosak/dokuwiki-plugin-fksdbexport#3]
V pornookně nechám pomocí Google vyhledat URL (`http://fykos.cz/o-nas/organizatori`), na stránce výsledků nikde tahle stránka není. (Čekal bych ji tam.) Další problém jsou prohlížeče bez JS, uživatelé pak nevidí žádný obsah.

Výše uvedené problémy jsou snesitelné v interní (jako po přihlášení i jako pro vnitřní použití) aplikaci, ale ne na veřejném webu.

Pro docílení stejného efektu navrhuji toto řešení:
- renderovat export do tabulky, např. jako s Dokuwiki templatem,
- upravit syntax pluginu, aby bylo možno připojit dekorační Java Script (tj. ten který je teď v těle templatu),
- dekorační JS použije data z tabulky a nahradí ji zvonky a píšťalkami (bells and whistles).

I bez JS bude obsah k dispozici (a může být formátovat pomocí prostého CSS).

**Comment by cevro** [comment]
menila sa URL takže asi google nestihol zareagova, nadpis nieje renderovaný cez JS takže, problém je na strane googlu.

Čo sa týka vypnutého JS našiel som štatistiku:
https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/

A podľa nej 1.1% má s týmto problém, radšej im vyhodím hlášku ako znepriemňovať 98.9% návštevníkom návštevu v podobe meniacej sa tabuľky na niečo iné. Ibaže umiestniť tabuľku do <noscript>, čo neviem či je povoľené.

**Comment by Werkov** [comment]
Díky za rychlou reakci :-)

(Jakým dotazem lze tedy tu stránku vyhledat? `FYKOS organizátoři` mi vrací jen orgy akcí, avšak ani starý ani nový seznam orgů.)

Generovat viditelnou stránku z metadat (atribut `data`) mi přijde koncepčně špatné (proto [nereaguji na tu statistiku](http://www.smbc-comics.com/comic/citation-needed) :-). Obzvlášť v tomto případě, kdy jde jen o seznam, který by se dal udělat pomocí HTML+CSS a drobného JS nakonec pro to "rozpohybování".

Vracet hlášku non-JS klientům, je minimální nutnost, pokud už se neshodneme na tom tabulkovo-nahrazovacím řešení. (Přistoupím na to, pokud nějak uvidím, že to vyhledávače (>= Google) indexují.)

**Comment by Werkov** [comment]
Hm, teď jsem zkusil googlící test znova a zdá se, že to nějak indexuje (ale ve snippetech na stránce výsledků se to nezobrazuje). Mým zbývajícím argumentem jsou archivovače -- pro ty by to však mělo být OK, dokud se nebudou data renderovaná JS stahovat asynchroně (což v verzi, kterou jsem viděl chválabohu nebylo :-)

**Comment by cevro** [comment]
Pre budúcnosť sa s JS renderom na prezenčnom webe nepočíta, a pravdepodobne ani na organizátorských Wiki. 

v PR https://github.com/fykosak/dokuwiki-plugin-fksdbexport/pull/5 je už zmazaný.
